#!/usr/bin/env python

import sys
try:
     import pygtk
     pygtk.require("2.0")
except:
      pass
try:
    import gtk
    import gtk.glade
except:
    sys.exit(1)

import os

from RapacheGtk.RapacheGui import MainWindow
from RapacheCore import Configuration


if __name__ == "__main__":    
         
    Configuration.APPPATH = "/usr/bin"
    Configuration.GLADEPATH = "/usr/share/rapache/Glade"        
    hwg = MainWindow( Configuration )
    gtk.main()
