#!/usr/bin/env python

import sys
import os.path

try:
     import pygtk
     pygtk.require("2.0")
except:
      pass
try:
    import gtk
    import gtk.glade
except:
    sys.exit(1)

import os

from RapacheGtk.RapacheGui import MainWindow
from RapacheCore import Configuration

if __name__ == "__main__":
    current_path = os.path.abspath(os.path.dirname(__file__))
    if ( os.path.exists( current_path+"/RapacheCore" ) ):
        #self-contained mode
        Configuration.APPPATH = os.path.abspath(os.path.dirname(__file__))
        Configuration.GLADEPATH = Configuration.APPPATH + "/Glade"        
    hwg = MainWindow( Configuration )
    gtk.main()
