#!/usr/bin/env python

# Rapache - Apache Configuration Tool
# Copyright (C) 2008 Stefano Forenza,  Jason Taylor, Emanuele Gentili
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os.path

try:
     import pygtk
     pygtk.require("2.0")
except:
      pass
try:
    import gtk
    import gtk.glade
except:
    sys.exit(1)

import os

from RapacheGtk.RapacheGui import MainWindow
from RapacheGtk.WarningWindow import WarningWindow
from RapacheCore import Configuration


if __name__ == "__main__":
		current_path = os.path.abspath(os.path.dirname(__file__))
		if ( os.path.exists( current_path+"/RapacheCore" ) ):
		    #self-contained mode
		    Configuration.APPPATH = os.path.abspath(os.path.dirname(__file__))
		    Configuration.GLADEPATH = Configuration.APPPATH + "/Glade"    

		if( os.path.isdir( Configuration.SITES_AVAILABLE_DIR ) and os.path.isdir( Configuration.SITES_ENABLED_DIR )):
	   		hwg = MainWindow()
			gtk.main()
		else: 
			ww = WarningWindow("Apache isn't installed. Rapache has nothing to manage.")   
			gtk.main()    
